JU_BASE = {
    "PPTI_14_15_3": {
        "N": "ROTONDE_14_5",
        "S": "ROTONDE_15_5",
        "TME": "PPTI_COMPUTER_ROOM_3",
    },
    "ROTONDE_14_5": {"DOWN": "ROTONDE_14_4"},
    "ROTONDE_14_4": {"E": "ROTONDE_24_4", "UP": "ROTONDE_14_5", "DOWN": "ROTONDE_14_3"},
    "ROTONDE_24_4": {"W": "ROTONDE_14_4", "DOWN": "ROTONDE_24_2"},
    "ROTONDE_24_2": {"E": "ROTONDE_34_2", "UP": "ROTONDE_24_4", "DOWN": "JU_24"},
    "ROTONDE_34_2": {"N": "DSI_33_34_2", "W": "ROTONDE_24_2", "DOWN": "JU_34"},
    "DSI_33_34_2": {"OUT": "JU_33", "DOWN": "JU_33"},
    "JU_33": {"N": "JU_32", "W": "JU_23", "S": "JU_34", "E": "JU_43"},
    "JU_32": {"W": "JU_22", "S": "JU_33", "E": "JU_42"},
    "JU_22": {"W": "JU_12", "S": "JU_23", "E": "JU_32", "UP": "ROTONDE_22_1"},
    "JU_12": {"S": "JU_13", "E": "JU_22", "UP": "ROTONDE_12_1"},
    "JU_13": {"N": "JU_12", "S": "JU_14", "E": "JU_23"},
    "JU_14": {"N": "JU_13", "E": "JU_24", "IN": "ROTONDE_14_4", "UP": "ROTONDE_14_4"},
    "JU_24": {
        "N": "JU_23",
        "W": "JU_14",
        "S": "JU_25",
        "E": "JU_34",
        "IN": "ROTONDE_24_2",
        "UP": "ROTONDE_24_2",
        "EVE": "STUDENTS_CORNER_OUTSIDE",
    },
    "JU_23": {
        "N": "JU_22",
        "W": "JU_13",
        "S": "STUDENTS_CORNER_OUTSIDE",
        "EVE": "STUDENTS_CORNER_OUTSIDE",
    },
    "STUDENTS_CORNER_OUTSIDE": {
        "S": "JU_24",
        "E": "STUDENTS_CORNER",
        "IN": "STUDENTS_CORNER",
    },
    "STUDENTS_CORNER": {
        "W": "STUDENTS_CORNER_OUTSIDE",
        "OUT": "STUDENTS_CORNER_OUTSIDE",
    },
    "JU_25": {
        "N": "JU_24",
        "S": "JU_26",
        "E": "JU_ZAMANSKI",
        "IN": "AMPHI_25",
        "UP": "ROTONDE_25_2",
        "DOWN": "MIR_SB",
        "ZAMANSKI": "JU_ZAMANSKI",
        "PATIO": "MIR_SB",
    },
    "JU_26": {
        "N": "JU_25",
        "W": "JU_16",
        "E": "CAMPUS_EXIT",
        "OUT": "CAMPUS_EXIT",
        "IN": "ROTONDE_26_2",
        "UP": "ROTONDE_26_2",
        "ZAMANSKI": "JU_ZAMANSKI",
    },
    "JU_16": {"N": "JU_15", "E": "JU_26"},
    "JU_15": {"S": "JU_16", "IN": "ROTONDE_15_4", "UP": "ROTONDE_15_4"},
    "ROTONDE_15_4": {"E": "ROTONDE_25_4", "UP": "ROTONDE_15_5", "DOWN": "ROTONDE_15_3"},
    "ROTONDE_25_4": {"W": "ROTONDE_15_4", "DOWN": "ROTONDE_25_2"},
    "ROTONDE_25_2": {"UP": "ROTONDE_25_4", "DOWN": "JU_25"},
    "ROTONDE_15_5": {"DOWN": "ROTONDE_15_4"},
    "ROTONDE_15_3": {
        "N": "PPTI_14_15_3",
        "IN": "PPTI_14_15_3",
        "UP": "ROTONDE_15_4",
        "DOWN": "JU_15",
    },
    "CAMPUS_EXIT": {
        "N": "JU_ZAMANSKI",
        "W": "JU_26",
        "E": "JU_46",
        "ZAMANSKI": "JU_ZAMANSKI",
    },
    "JU_ZAMANSKI": {
        "N": "JU_34",
        "W": "JU_25",
        "S": "CAMPUS_EXIT",
        "E": "JU_45",
        "OUT": "CAMPUS_EXIT",
    },
    "JU_34": {
        "N": "JU_33",
        "W": "JU_24",
        "S": "JU_ZAMANSKI",
        "E": "JU_44",
        "UP": "ROTONDE_34_2",
        "ZAMANSKI": "JU_ZAMANSKI",
    },
    "JU_44": {
        "N": "JU_43",
        "W": "JU_34",
        "S": "JU_45",
        "E": "JU_54",
        "ZAMANSKI": "JU_ZAMANSKI",
        "TUMULUS": "JU_TUMULUS",
    },
    "JU_43": {"N": "JU_42", "W": "JU_33", "S": "JU_44"},
    "JU_42": {"W": "JU_32", "S": "JU_43"},
    "JU_45": {
        "N": "JU_44",
        "W": "JU_ZAMANSKI",
        "S": "JU_46",
        "OUT": "CAMPUS_EXIT",
        "ZAMANSKI": "JU_ZAMANSKI",
        "TUMULUS": "JU_TUMULUS",
    },
    "JU_46": {
        "N": "JU_45",
        "W": "CAMPUS_EXIT",
        "E": "JU_56",
        "OUT": "CAMPUS_EXIT",
        "ZAMANSKI": "JU_ZAMANSKI",
    },
    "JU_56": {"N": "JU_55", "W": "JU_46", "E": "JU_66", "ISIR": "ISIR_OUTSIDE"},
    "JU_55": {
        "N": "JU_54",
        "S": "JU_56",
        "E": "JU_65",
        "ISIR": "ISIR_OUTSIDE",
        "TUMULUS": "JU_TUMULUS",
    },
    "JU_54": {
        "N": "JU_53",
        "W": "JU_44",
        "S": "JU_55",
        "E": "JU_ATRIUM_ESPLANADE",
        "TUMULUS": "JU_TUMULUS",
    },
    "JU_53": {"S": "JU_54", "E": "JU_ATRIUM_ESPLANADE"},
    "JU_ATRIUM_ESPLANADE": {
        "W": "JU_54",
        "E": "JU_ATRIUM_HALL",
        "IN": "JU_ATRIUM_HALL",
    },
    "JU_ATRIUM_HALL": {
        "W": "JU_ATRIUM_ESPLANADE",
        "OUT": "JU_ATRIUM_ESPLANADE",
        "UP": "JU_ATRIUM_1ST_FLOOR",
    },
    "JU_ATRIUM_1ST_FLOOR": {"UP": "JU_ATRIUM_2ND_FLOOR", "DOWN": "JU_ATRIUM_HALL"},
    "JU_ATRIUM_2ND_FLOOR": {"UP": "JU_ATRIUM_3RD_FLOOR", "DOWN": "JU_ATRIUM_1ST_FLOOR"},
    "JU_ATRIUM_3RD_FLOOR": {"UP": "JU_ATRIUM_4TH_FLOOR", "DOWN": "JU_ATRIUM_2ND_FLOOR"},
    "JU_ATRIUM_4TH_FLOOR": {
        "UP": "JU_ATRIUM_5TH_FLOOR",
        "DOWN": "JU_ATRIUM_3RD_FLOOR",
        "SALLE": "JU_ATRIUM_TP",
    },
    "JU_ATRIUM_5TH_FLOOR": {"DOWN": "JU_ATRIUM_4TH_FLOOR"},
    "JU_ATRIUM_TP": {"OUT": "JU_ATRIUM_4TH_FLOOR"},
    "JU_TUMULUS": {},
    "JU_65": {"W": "JU_55", "S": "JU_66"},
    "JU_66": {"N": "JU_65", "W": "JU_56", "E": "JU_ESCLANGON"},
    "JU_ESCLANGON": {"W": "JU_66", "OUT": "JU_66"},
    "ISIR_OUTSIDE": {
        "N": "JU_55",
        "S": "JU_56",
        "E": "ISIR_HALL",
        "IN": "ISIR_HALL",
        "ISIR": "ISIR_HALL",
    },
    "ISIR_HALL": {"N": "ISIR_J05", "OUT": "ISIR_OUTSIDE", "UP": "ISIR_UPPER"},
    "ISIR_J05": {"S": "ISIR_HALL", "OUT": "ISIR_HALL"},
    "ISIR_UPPER": {
        "N": "ISIR_H04",
        "W": "ISIR_H20",
        "E": "ISIR_H08",
        "DOWN": "ISIR_HALL",
    },
    "ISIR_H04": {"S": "ISIR_UPPER", "OUT": "ISIR_UPPER"},
    "ISIR_H20": {"E": "ISIR_UPPER", "OUT": "ISIR_UPPER"},
    "ISIR_H08": {"W": "ISIR_UPPER", "OUT": "ISIR_UPPER"},
    "ROTONDE_26_2": {"UP": "ROTONDE_26_4", "DOWN": "JU_26"},
    "ROTONDE_26_4": {"DOWN": "ROTONDE_26_2"},
    "AMPHI_25": {"S": "MIR_SB", "E": "JU_25", "UP": "JU_25", "PATIO": "MIR_SB"},
    "MIR_SB": {"N": "AMPHI_25", "E": "JU_25", "UP": "JU_25"},
    "ROTONDE_12_1": {"E": "LPNHE_12_22_1", "DOWN": "JU_12"},
    "LPNHE_12_22_1": {"W": "ROTONDE_12_1", "E": "ROTONDE_22_1"},
    "ROTONDE_22_1": {"W": "LPNHE_12_22_1", "DOWN": "JU_22"},
    "ROTONDE_14_3": {"S": "PPTI_14_15_3", "UP": "ROTONDE_14_4", "DOWN": "JU_14"},
    "PPTI_COMPUTER_ROOM_3": {"OUT": "PPTI_14_15_3"},
}

SB_BASE = {
    "SB_55": {
        "N": "SB_54",
        "W": "SB_CICSU_ENTRANCE",
        "S": "SB_56",
        "IN": "SB_CICSU_ENTRANCE",
    },
    "SB_54": {"N": "SB_53_54", "W": "SB_44", "S": "SB_55"},
    "SB_53_54": {
        "N": "SB_53",
        "S": "SB_54",
        "E": "SB_ATRIUM_GARDEN",
        "IN": "SB_ATRIUM_GARDEN",
    },
    "SB_53": {"S": "SB_53_54"},
    "SB_ATRIUM_GARDEN": {
        "N": "SB_ATRIUM_ENTRY",
        "W": "SB_53_54",
        "OUT": "SB_53_54",
        "IN": "SB_ATRIUM_ENTRY",
    },
    "SB_ATRIUM_ENTRY": {"S": "SB_ATRIUM_GARDEN", "OUT": "SB_ATRIUM_GARDEN"},
    "SB_44": {
        "N": "SB_44_ROTONDE",
        "W": "SB_34_44",
        "E": "SB_54",
        "IN": "SB_44_ROTONDE",
    },
    "SB_44_ROTONDE": {"W": "SB_COMPUTER_ROOM", "S": "SB_44", "OUT": "SB_44"},
    "SB_COMPUTER_ROOM": {"E": "SB_44_ROTONDE", "OUT": "SB_44_ROTONDE"},
    "SB_34_44": {"W": "SB_34", "S": "SB_PARKING", "E": "SB_44"},
    "SB_34": {"N": "SB_33_34", "W": "SB_24", "E": "SB_34_44"},
    "SB_33_34": {"N": "SB_33", "W": "SB_23_24", "S": "SB_34"},
    "SB_33": {"N": "SB_32_33", "W": "SB_23", "S": "SB_33_34", "E": "SB_33_43"},
    "SB_32_33": {"N": "SB_32", "W": "SB_22_23", "S": "SB_33"},
    "SB_32": {"W": "SB_22", "S": "SB_32_33"},
    "SB_22": {"S": "SB_22_23", "E": "SB_32", "IN": "LPNHE_HALL"},
    "SB_22_23": {"N": "SB_22", "S": "SB_23", "E": "SB_32_33"},
    "SB_23": {"N": "SB_22_23", "W": "SB_23_W", "S": "SB_23_24", "E": "SB_33"},
    "SB_23_W": {"E": "SB_23", "OUT": "SB_23"},
    "SB_23_24": {"N": "SB_23", "S": "SB_24", "E": "SB_33_34"},
    "SB_24": {"N": "SB_23_24", "S": "SB_26", "E": "SB_34"},
    "SB_26": {"N": "SB_24", "S": "SB_26_DEADEND"},
    "SB_26_DEADEND": {"N": "SB_26"},
    "LPNHE_HALL": {"S": "LPNHE_HALLWAY", "OUT": "SB_22"},
    "LPNHE_HALLWAY": {"N": "LPNHE_HALL"},
    "SB_33_43": {"N": "SB_33_43_DEADEND", "W": "SB_33", "E": "SB_43"},
    "SB_33_43_DEADEND": {"S": "SB_33_43", "OUT": "SB_33_43"},
    "SB_43": {
        "W": "SB_33_43",
        "S": "BACHELOR_LIBRARY_HALL",
        "E": "SB_43_53",
        "IN": "BACHELOR_LIBRARY_HALL",
    },
    "BACHELOR_LIBRARY_HALL": {"N": "SB_43", "OUT": "SB_43"},
    "SB_43_53": {"N": "SB_43_53_DEADEND", "W": "SB_43"},
    "SB_43_53_DEADEND": {"S": "SB_43_53", "OUT": "SB_43_53"},
    "SB_PARKING": {"N": "SB_34_44"},
    "SB_CICSU_ENTRANCE": {"E": "SB_55", "OUT": "SB_55"},
    "SB_56": {"N": "SB_55"},
}

NAME_GRAPH = SB_BASE
NAME_GRAPH.update(JU_BASE)
