JU_BASE = {
    "PPTI_14_15_3": {
        "14": "ROTONDE_14_5",
        "15": "ROTONDE_15_5",
        "N": "ROTONDE_14_5",
        "S": "ROTONDE_15_5",
        "TME": "PPTI_COMPUTER_ROOM_3",
        "TP": "PPTI_COMPUTER_ROOM_3",
    },
    "ROTONDE_14_5": {"DOWN": "ROTONDE_14_4"},
    "ROTONDE_14_4": {
        "24": "ROTONDE_24_4",
        "FORMATION": "ROTONDE_24_4",
        "CONTINUE": "ROTONDE_24_4",
        "E": "ROTONDE_24_4",
        "DOWN": "ROTONDE_14_3",
        "UP": "ROTONDE_14_5",
    },
    "ROTONDE_24_4": {
        "DOWN": "ROTONDE_24_2",
        "14": "ROTONDE_14_4",
        "COULOIR": "ROTONDE_14_4",
        "FORMATION": "ROTONDE_14_4",
        "CONTINUE": "ROTONDE_14_4",
        "W": "ROTONDE_14_4",
    },
    "ROTONDE_24_2": {
        "DOWN": "JU_24",
        "UP": "ROTONDE_24_4",
        "34": "ROTONDE_34_2",
        "E": "ROTONDE_34_2",
    },
    "JU_24": {
        "IN": "ROTONDE_24_2",
        "UP": "ROTONDE_24_2",
        "SE": "JU_ZAMANSKI",
        "W": "JU_14",
        "S": "JU_25",
        "14": "JU_14",
        "25": "JU_25",
        "34": "JU_34",
        "23": "JU_23",
        "N": "JU_23",
        "E": "JU_34",
        "ESPACE": "STUDENTS_CORNER_OUTSIDE",
        "VIE": "STUDENTS_CORNER_OUTSIDE",
        "EVE": "STUDENTS_CORNER_OUTSIDE",
    },
    "JU_ZAMANSKI": {
        "S": "CAMPUS_EXIT",
        "GRILLE": "CAMPUS_EXIT",
        "OUT": "CAMPUS_EXIT",
        "SORTIE": "CAMPUS_EXIT",
        "N": "JU_34",
        "34": "JU_34",
        "25": "JU_25",
        "W": "JU_25",
        "26": "JU_26",
        "SW": "JU_26",
        "45": "JU_45",
        "E": "JU_45",
        "24": "JU_24",
        "NW": "JU_24",
        "44": "JU_44",
        "NE": "JU_44",
        "46": "JU_46",
        "SE": "JU_46",
    },
    "CAMPUS_EXIT": {
        "46": "JU_46",
        "E": "JU_46",
        "NE": "JU_25",
        "25": "JU_25",
        "W": "JU_26",
        "26": "JU_26",
        "N": "JU_ZAMANSKI",
        "TOUR": "JU_ZAMANSKI",
        "ESPLANADE": "JU_ZAMANSKI",
        "ZAMANSKI": "JU_ZAMANSKI",
    },
    "JU_46": {
        "N": "JU_45",
        "45": "JU_45",
        "E": "JU_56",
        "56": "JU_56",
        "W": "CAMPUS_EXIT",
        "GRILLE": "CAMPUS_EXIT",
        "OUT": "CAMPUS_EXIT",
        "SORTIE": "CAMPUS_EXIT",
        "NW": "JU_ZAMANSKI",
        "ZAMANSKI": "JU_ZAMANSKI",
        "ESPLANADE": "JU_ZAMANSKI",
        "CENTRALE": "JU_ZAMANSKI",
    },
    "JU_45": {
        "N": "JU_44",
        "44": "JU_44",
        "S": "JU_46",
        "46": "JU_46",
        "W": "JU_ZAMANSKI",
        "ZAMANSKI": "JU_ZAMANSKI",
        "ESPLANADE": "JU_ZAMANSKI",
        "CENTRALE": "JU_ZAMANSKI",
        "SW": "CAMPUS_EXIT",
        "GRILLE": "CAMPUS_EXIT",
        "OUT": "CAMPUS_EXIT",
        "SORTIE": "CAMPUS_EXIT",
        "NE": "JU_TUMULUS",
        "54": "JU_54",
        "NW": "JU_34",
        "34": "JU_34",
        "TUMULUS": "JU_TUMULUS",
        "AUDITORIUM": "JU_TUMULUS",
        "CICSU": "JU_TUMULUS",
    },
    "JU_44": {
        "N": "JU_43",
        "43": "JU_43",
        "S": "JU_45",
        "45": "JU_45",
        "E": "JU_54",
        "54": "JU_54",
        "W": "JU_34",
        "34": "JU_34",
        "SW": "JU_ZAMANSKI",
        "ZAMANSKI": "JU_ZAMANSKI",
        "ESPLANADE": "JU_ZAMANSKI",
        "CENTRALE": "JU_ZAMANSKI",
        "SE": "JU_TUMULUS",
        "53": "JU_53",
        "TUMULUS": "JU_TUMULUS",
        "AUDITORIUM": "JU_TUMULUS",
        "CICSU": "JU_TUMULUS",
    },
    "JU_43": {
        "N": "JU_42",
        "42": "JU_42",
        "S": "JU_44",
        "44": "JU_44",
        "W": "JU_33",
        "33": "JU_33",
    },
    "JU_42": {"W": "JU_32", "32": "JU_32", "S": "JU_43", "43": "JU_43"},
    "JU_32": {
        "12": "JU_22",
        "W": "JU_22",
        "42": "JU_42",
        "E": "JU_42",
        "33": "JU_33",
        "S": "JU_33",
    },
    "JU_22": {
        "UP": "ROTONDE_22_1",
        "LPNHE": "ROTONDE_22_1",
        "12": "JU_12",
        "W": "JU_12",
        "32": "JU_32",
        "E": "JU_32",
        "S": "JU_23",
        "23": "JU_23",
    },
    "ROTONDE_22_1": {
        "12": "LPNHE_12_22_1",
        "LPNHE": "LPNHE_12_22_1",
        "COULOIR": "LPNHE_12_22_1",
        "W": "LPNHE_12_22_1",
        "DOWN": "JU_22",
    },
    "LPNHE_12_22_1": {
        "BUREAU": "LPNHE_OFFICE_117",
        "117": "LPNHE_OFFICE_117",
        "CAF\u00c9T\u00c9RIA": "LPNHE_CAFET",
        "12": "ROTONDE_12_1",
        "W": "ROTONDE_12_1",
        "22": "ROTONDE_22_1",
        "E": "ROTONDE_22_1",
    },
    "LPNHE_OFFICE_117": {"OUT": "LPNHE_12_22_1", "COULOIR": "LPNHE_12_22_1"},
    "LPNHE_CAFET": {
        "OUT": "LPNHE_12_22_1",
        "COULOIR": "LPNHE_12_22_1",
        "UP": "LPNHE_12_22_2",
    },
    "LPNHE_12_22_2": {
        "DISPOSITIFS": "LPNHE_MACHINE_ROOM",
        "EXP\u00c9RIMENTAUX": "LPNHE_MACHINE_ROOM",
        "CAF\u00c9T\u00c9RIA": "LPNHE_CAFET",
        "DOWN": "LPNHE_CAFET",
    },
    "LPNHE_MACHINE_ROOM": {"OUT": "LPNHE_12_22_2", "COULOIR": "LPNHE_12_22_2"},
    "ROTONDE_12_1": {
        "22": "LPNHE_12_22_1",
        "LPNHE": "LPNHE_12_22_1",
        "COULOIR": "LPNHE_12_22_1",
        "E": "LPNHE_12_22_1",
        "DOWN": "JU_12",
    },
    "JU_12": {
        "UP": "ROTONDE_12_1",
        "LPNHE": "ROTONDE_12_1",
        "E": "JU_22",
        "22": "JU_22",
        "S": "JU_13",
        "13": "JU_13",
    },
    "JU_13": {
        "E": "JU_23",
        "23": "JU_23",
        "N": "JU_12",
        "12": "JU_12",
        "S": "JU_14",
        "14": "JU_14",
        "SW": "JU_24",
        "24": "JU_24",
    },
    "JU_23": {
        "13": "JU_13",
        "W": "JU_13",
        "22": "JU_22",
        "N": "JU_22",
        "33": "JU_33",
        "S": "STUDENTS_CORNER_OUTSIDE",
        "ESPACE": "STUDENTS_CORNER_OUTSIDE",
        "VIE": "STUDENTS_CORNER_OUTSIDE",
        "EVE": "STUDENTS_CORNER_OUTSIDE",
        "24": "JU_24",
    },
    "JU_33": {
        "N": "JU_32",
        "32": "JU_32",
        "S": "JU_34",
        "34": "JU_34",
        "E": "JU_43",
        "43": "JU_43",
        "W": "JU_23",
        "23": "JU_23",
    },
    "JU_34": {
        "N": "JU_33",
        "33": "JU_33",
        "S": "JU_ZAMANSKI",
        "ZAMANSKI": "JU_ZAMANSKI",
        "TOUR": "JU_ZAMANSKI",
        "CENTRALE": "JU_ZAMANSKI",
        "ESPLANADE": "JU_ZAMANSKI",
        "E": "JU_44",
        "44": "JU_44",
        "W": "JU_24",
        "24": "JU_24",
        "SW": "JU_25",
        "25": "JU_25",
        "SE": "JU_45",
        "45": "JU_45",
        "UP": "ROTONDE_34_2",
        "DSI": "ROTONDE_34_2",
    },
    "JU_25": {
        "IN": "AMPHI_25",
        "UP": "ROTONDE_25_2",
        "E": "JU_ZAMANSKI",
        "ZAMANSKI": "JU_ZAMANSKI",
        "ESPLANADE": "JU_ZAMANSKI",
        "CENTRALE": "JU_ZAMANSKI",
        "SORTIE": "CAMPUS_EXIT",
        "GRILLE": "CAMPUS_EXIT",
        "SE": "CAMPUS_EXIT",
        "S": "JU_26",
        "26": "JU_26",
        "N": "JU_24",
        "24": "JU_24",
        "DOWN": "MIR_SB",
        "ESCALIER": "MIR_SB",
        "BIBLIOTHEQUE": "MIR_SB",
        "MIR": "MIR_SB",
        "PATIO": "MIR_SB",
        "SW": "MIR_SB",
        "AMPHI": "AMPHI_25",
    },
    "AMPHI_25": {
        "E": "JU_25",
        "UP": "JU_25",
        "25": "JU_25",
        "S": "MIR_SB",
        "BIBLIOTHEQUE": "MIR_SB",
        "MIR": "MIR_SB",
        "PATIO": "MIR_SB",
        "SORTIE": "MIR_SB",
        "SECOURS": "MIR_SB",
    },
    "MIR_SB": {
        "N": "AMPHI_25",
        "AMPHI": "AMPHI_25",
        "UP": "JU_25",
        "E": "JU_25",
        "25": "JU_25",
    },
    "ROTONDE_25_2": {"DOWN": "JU_25", "UP": "ROTONDE_25_4"},
    "ROTONDE_25_4": {
        "DOWN": "ROTONDE_25_2",
        "W": "ROTONDE_15_4",
        "15": "ROTONDE_15_4",
        "IMJ": "ROTONDE_15_4",
    },
    "ROTONDE_15_4": {
        "DOWN": "ROTONDE_15_3",
        "UP": "ROTONDE_15_5",
        "E": "ROTONDE_25_4",
        "25": "ROTONDE_25_4",
        "IMJ": "ROTONDE_25_4",
    },
    "ROTONDE_15_3": {
        "DOWN": "JU_15",
        "UP": "ROTONDE_15_4",
        "N": "PPTI_14_15_3",
        "PPTI": "PPTI_14_15_3",
        "14": "PPTI_14_15_3",
        "IN": "PPTI_14_15_3",
    },
    "JU_15": {"IN": "ROTONDE_15_4", "UP": "ROTONDE_15_4", "S": "JU_16", "16": "JU_16"},
    "JU_16": {"N": "JU_15", "15": "JU_15", "E": "JU_26", "26": "JU_26"},
    "JU_26": {
        "IN": "ROTONDE_26_2",
        "UP": "ROTONDE_26_2",
        "N": "JU_25",
        "25": "JU_25",
        "W": "JU_16",
        "16": "JU_16",
        "NE": "JU_ZAMANSKI",
        "ZAMANSKI": "JU_ZAMANSKI",
        "ESPLANADE": "JU_ZAMANSKI",
        "E": "CAMPUS_EXIT",
        "GRILLE": "CAMPUS_EXIT",
        "OUT": "CAMPUS_EXIT",
        "SORTIE": "CAMPUS_EXIT",
    },
    "ROTONDE_26_2": {"DOWN": "JU_26", "UP": "ROTONDE_26_4"},
    "ROTONDE_26_4": {"DOWN": "ROTONDE_26_2"},
    "ROTONDE_15_5": {"DOWN": "ROTONDE_15_4"},
    "ROTONDE_34_2": {
        "DOWN": "JU_34",
        "N": "DSI_33_34_2",
        "DSI": "DSI_33_34_2",
        "COULOIR": "DSI_33_34_2",
        "24": "ROTONDE_24_2",
        "W": "ROTONDE_24_2",
    },
    "DSI_33_34_2": {"DOWN": "JU_33", "OUT": "JU_33"},
    "STUDENTS_CORNER_OUTSIDE": {
        "24": "JU_24",
        "S": "JU_24",
        "14": "JU_14",
        "SW": "JU_14",
        "13": "JU_13",
        "NW": "JU_13",
        "E": "STUDENTS_CORNER",
        "IN": "STUDENTS_CORNER",
        "ESPACE": "STUDENTS_CORNER",
        "VIE": "STUDENTS_CORNER",
    },
    "JU_14": {
        "IN": "ROTONDE_14_4",
        "UP": "ROTONDE_14_4",
        "E": "JU_24",
        "24": "JU_24",
        "N": "JU_13",
        "13": "JU_13",
        "NE": "JU_23",
        "23": "JU_23",
    },
    "STUDENTS_CORNER": {
        "W": "STUDENTS_CORNER_OUTSIDE",
        "OUT": "STUDENTS_CORNER_OUTSIDE",
    },
    "JU_54": {
        "N": "JU_53",
        "53": "JU_53",
        "S": "JU_55",
        "55": "JU_55",
        "W": "JU_44",
        "44": "JU_44",
        "E": "JU_ATRIUM_ESPLANADE",
        "NE": "JU_ATRIUM_ESPLANADE",
        "ATRIUM": "JU_ATRIUM_ESPLANADE",
        "ESPLANADE": "JU_ATRIUM_ESPLANADE",
        "TUMULUS": "JU_TUMULUS",
        "AUDITORIUM": "JU_TUMULUS",
        "CICSU": "JU_TUMULUS",
    },
    "JU_53": {
        "S": "JU_54",
        "54": "JU_54",
        "ESPLANADE": "JU_ATRIUM_ESPLANADE",
        "ATRIUM": "JU_ATRIUM_ESPLANADE",
        "E": "JU_ATRIUM_ESPLANADE",
        "SE": "JU_ATRIUM_ESPLANADE",
    },
    "JU_ATRIUM_ESPLANADE": {
        "54": "JU_54",
        "SW": "JU_54",
        "53": "JU_53",
        "NW": "JU_53",
        "W": "JU_54",
        "E": "JU_ATRIUM_HALL",
        "ATRIUM": "JU_ATRIUM_HALL",
        "IN": "JU_ATRIUM_HALL",
        "HALL": "JU_ATRIUM_HALL",
    },
    "JU_ATRIUM_HALL": {
        "OUT": "JU_ATRIUM_ESPLANADE",
        "W": "JU_ATRIUM_ESPLANADE",
        "ESCALIER": "JU_ATRIUM_1ST_FLOOR",
        "UP": "JU_ATRIUM_1ST_FLOOR",
        "COULOIR": "JU_ATRIUM_TURQUOISE",
        "TURQUOISE": "JU_ATRIUM_TURQUOISE",
    },
    "JU_ATRIUM_1ST_FLOOR": {
        "BUREAU": "JU_ATRIUM_112",
        "R\u00c9SEAU": "JU_ATRIUM_112",
        "112": "JU_ATRIUM_112",
        "UP": "JU_ATRIUM_2ND_FLOOR",
        "DOWN": "JU_ATRIUM_HALL",
        "HALL": "JU_ATRIUM_HALL",
    },
    "JU_ATRIUM_112": {
        "COULOIR": "JU_ATRIUM_1ST_FLOOR",
        "COURSIVE": "JU_ATRIUM_1ST_FLOOR",
        "OUT": "JU_ATRIUM_1ST_FLOOR",
        "ATRIUM": "JU_ATRIUM_1ST_FLOOR",
    },
    "JU_ATRIUM_2ND_FLOOR": {
        "DOWN": "JU_ATRIUM_1ST_FLOOR",
        "UP": "JU_ATRIUM_3RD_FLOOR",
        "LOCAL": "JU_ATRIUM_STORAGE",
        "TECHNIQUE": "JU_ATRIUM_STORAGE",
        "D\u00c9BARRAS": "JU_ATRIUM_STORAGE",
    },
    "JU_ATRIUM_3RD_FLOOR": {"DOWN": "JU_ATRIUM_2ND_FLOOR", "UP": "JU_ATRIUM_4TH_FLOOR"},
    "JU_ATRIUM_4TH_FLOOR": {
        "DOWN": "JU_ATRIUM_3RD_FLOOR",
        "UP": "JU_ATRIUM_5TH_FLOOR",
        "SALLE": "JU_ATRIUM_TP",
        "TP": "JU_ATRIUM_TP",
    },
    "JU_ATRIUM_5TH_FLOOR": {"DOWN": "JU_ATRIUM_4TH_FLOOR"},
    "JU_ATRIUM_TP": {
        "COULOIR": "JU_ATRIUM_4TH_FLOOR",
        "COURSIVE": "JU_ATRIUM_4TH_FLOOR",
        "OUT": "JU_ATRIUM_4TH_FLOOR",
        "ATRIUM": "JU_ATRIUM_4TH_FLOOR",
    },
    "JU_ATRIUM_STORAGE": {
        "COULOIR": "JU_ATRIUM_2ND_FLOOR",
        "COURSIVE": "JU_ATRIUM_2ND_FLOOR",
        "OUT": "JU_ATRIUM_2ND_FLOOR",
    },
    "JU_ATRIUM_TURQUOISE": {"OUT": "JU_ATRIUM_HALL", "HALL": "JU_ATRIUM_HALL"},
    "JU_55": {
        "TUMULUS": "JU_TUMULUS",
        "AUDITORIUM": "JU_TUMULUS",
        "CICSU": "JU_TUMULUS",
        "NW": "JU_TUMULUS",
        "ISIR": "ISIR_OUTSIDE",
        "SE": "ISIR_OUTSIDE",
        "PYRAMIDE": "ISIR_OUTSIDE",
        "N": "JU_54",
        "54": "JU_54",
        "S": "JU_56",
        "56": "JU_56",
        "E": "JU_65",
        "65": "JU_65",
    },
    "JU_TUMULUS": {
        "44": "JU_44",
        "NW": "JU_44",
        "45": "JU_45",
        "SW": "JU_44",
        "54": "JU_54",
        "NE": "JU_54",
        "55": "JU_55",
        "SE": "JU_54",
    },
    "ISIR_OUTSIDE": {
        "E": "ISIR_HALL",
        "IN": "ISIR_HALL",
        "ISIR": "ISIR_HALL",
        "PYRAMIDE": "ISIR_HALL",
        "HALL": "ISIR_HALL",
        "55": "JU_55",
        "56": "JU_56",
        "N": "JU_55",
        "S": "JU_56",
    },
    "ISIR_HALL": {
        "OUT": "ISIR_OUTSIDE",
        "J13": "ISIR_J13",
        "J15": "ISIR_J15",
        "J11": "ISIR_J11",
        "J05": "ISIR_J05",
        "N": "ISIR_J05",
        "UP": "ISIR_UPPER",
        "CAF\u00c9T\u00c9RIA": "ISIR_CAFET",
    },
    "ISIR_J13": {"OUT": "ISIR_HALL", "HALL": "ISIR_HALL", "N": "ISIR_HALL"},
    "ISIR_J15": {"OUT": "ISIR_HALL", "HALL": "ISIR_HALL", "N": "ISIR_HALL"},
    "ISIR_J11": {"OUT": "ISIR_HALL", "HALL": "ISIR_HALL", "W": "ISIR_HALL"},
    "ISIR_J05": {"OUT": "ISIR_HALL", "HALL": "ISIR_HALL", "S": "ISIR_HALL"},
    "ISIR_UPPER": {
        "DOWN": "ISIR_HALL",
        "H04": "ISIR_H04",
        "H08": "ISIR_H08",
        "H20": "ISIR_H20",
        "W": "ISIR_H20",
        "N": "ISIR_H04",
        "E": "ISIR_H08",
    },
    "ISIR_H04": {"OUT": "ISIR_UPPER", "S": "ISIR_UPPER", "COURSIVE": "ISIR_UPPER"},
    "ISIR_H08": {"OUT": "ISIR_UPPER", "W": "ISIR_UPPER", "COURSIVE": "ISIR_UPPER"},
    "ISIR_H20": {"OUT": "ISIR_UPPER", "E": "ISIR_UPPER", "COURSIVE": "ISIR_UPPER"},
    "ISIR_CAFET": {"OUT": "ISIR_HALL", "HALL": "ISIR_HALL", "W": "ISIR_HALL"},
    "JU_56": {
        "ISIR": "ISIR_OUTSIDE",
        "NE": "ISIR_OUTSIDE",
        "PYRAMIDE": "ISIR_OUTSIDE",
        "N": "JU_55",
        "55": "JU_55",
        "E": "JU_66",
        "66": "JU_66",
        "W": "JU_46",
        "46": "JU_46",
    },
    "JU_66": {
        "N": "JU_65",
        "65": "JU_65",
        "W": "JU_56",
        "56": "JU_56",
        "E": "JU_ESCLANGON",
        "ESCLANGON": "JU_ESCLANGON",
    },
    "JU_65": {"S": "JU_66", "66": "JU_56", "W": "JU_55", "55": "JU_55"},
    "JU_ESCLANGON": {"W": "JU_66", "OUT": "JU_66", "66": "JU_66"},
    "ROTONDE_14_3": {
        "15": "PPTI_14_15_3",
        "PPTI": "PPTI_14_15_3",
        "S": "PPTI_14_15_3",
        "DOWN": "JU_14",
        "UP": "ROTONDE_14_4",
    },
    "PPTI_COMPUTER_ROOM_3": {"OUT": "PPTI_14_15_3"},
}

SB_BASE = {
    "SB_26": {"N": "SB_24", "S": "SB_26_DEADEND"},
    "SB_24": {"E": "SB_34", "N": "SB_23_24", "S": "SB_26"},
    "SB_34": {"E": "SB_34_44", "W": "SB_24", "N": "SB_33_34"},
    "SB_34_44": {"W": "SB_34", "E": "SB_44", "S": "SB_PARKING"},
    "SB_44": {
        "W": "SB_34_44",
        "E": "SB_54",
        "N": "SB_44_ROTONDE",
        "IN": "SB_44_ROTONDE",
        "PORTE": "SB_44_ROTONDE",
    },
    "SB_54": {"N": "SB_53_54", "W": "SB_44", "S": "SB_55"},
    "SB_53_54": {
        "N": "SB_53",
        "E": "SB_ATRIUM_GARDEN",
        "JARDIN": "SB_ATRIUM_GARDEN",
        "JARDINET": "SB_ATRIUM_GARDEN",
        "GRILLE": "SB_ATRIUM_GARDEN",
        "OUVERTURE": "SB_ATRIUM_GARDEN",
        "COUR": "SB_ATRIUM_GARDEN",
        "S": "SB_54",
        "IN": "SB_ATRIUM_GARDEN",
    },
    "SB_53": {"S": "SB_53_54"},
    "SB_ATRIUM_GARDEN": {
        "OUT": "SB_53_54",
        "COULOIR": "SB_53_54",
        "W": "SB_53_54",
        "GRILLE": "SB_53_54",
        "VOIE": "SB_53_54",
        "CIRCULATION": "SB_53_54",
        "FEN\u00caTRE": "SB_ATRIUM_ENTRY",
        "N": "SB_ATRIUM_ENTRY",
        "IN": "SB_ATRIUM_ENTRY",
    },
    "SB_ATRIUM_ENTRY": {
        "OUT": "SB_ATRIUM_GARDEN",
        "S": "SB_ATRIUM_GARDEN",
        "JARDIN": "SB_ATRIUM_GARDEN",
    },
    "SB_55": {
        "N": "SB_54",
        "W": "SB_CICSU_ENTRANCE",
        "PORTE": "SB_CICSU_ENTRANCE",
        "CICSU": "SB_CICSU_ENTRANCE",
        "IN": "SB_CICSU_ENTRANCE",
        "S": "SB_56",
    },
    "SB_CICSU_ENTRANCE": {"OUT": "SB_55", "E": "SB_55"},
    "SB_56": {"N": "SB_55"},
    "SB_44_ROTONDE": {
        "OUT": "SB_44",
        "S": "SB_44",
        "TME": "SB_COMPUTER_ROOM",
        "PORTE": "SB_COMPUTER_ROOM",
        "W": "SB_COMPUTER_ROOM",
    },
    "SB_COMPUTER_ROOM": {"OUT": "SB_44_ROTONDE", "E": "SB_44_ROTONDE"},
    "SB_PARKING": {"N": "SB_34_44"},
    "SB_33_34": {"S": "SB_34", "N": "SB_33", "W": "SB_23_24"},
    "SB_33": {
        "W": "SB_23",
        "S": "SB_33_34",
        "N": "SB_32_33",
        "PASSAGE": "SB_33_43",
        "E": "SB_33_43",
        "JARDIN": "SB_23",
        "JARDINET": "SB_23",
    },
    "SB_23": {"E": "SB_33", "N": "SB_22_23", "S": "SB_23_24", "W": "SB_23_W"},
    "SB_22_23": {"N": "SB_22", "S": "SB_23", "E": "SB_32_33"},
    "SB_22": {
        "S": "SB_22_23",
        "E": "SB_32",
        "LABORATOIRE": "LPNHE_HALL",
        "LABO": "LPNHE_HALL",
        "IN": "LPNHE_HALL",
        "LPNHE": "LPNHE_HALL",
    },
    "SB_32": {"S": "SB_32_33", "W": "SB_22"},
    "SB_32_33": {"W": "SB_22_23", "N": "SB_32", "S": "SB_33"},
    "LPNHE_HALL": {"OUT": "SB_22", "COULOIR": "LPNHE_HALLWAY", "S": "LPNHE_HALLWAY"},
    "LPNHE_HALLWAY": {
        "N": "LPNHE_HALL",
        "RC-13": "LPNHE_RC13",
        "13": "LPNHE_RC13",
        "RC-14": "LPNHE_RC14",
        "14": "LPNHE_RC14",
        "RC-17": "LPNHE_RC17",
        "17": "LPNHE_RC17",
        "RC-19": "LPNHE_RC19",
        "19": "LPNHE_RC19",
    },
    "LPNHE_RC13": {
        "OUT": "LPNHE_HALLWAY",
        "COULOIR": "LPNHE_HALLWAY",
        "W": "LPNHE_HALLWAY",
    },
    "LPNHE_RC14": {
        "OUT": "LPNHE_HALLWAY",
        "COULOIR": "LPNHE_HALLWAY",
        "W": "LPNHE_HALLWAY",
    },
    "LPNHE_RC17": {
        "OUT": "LPNHE_HALLWAY",
        "COULOIR": "LPNHE_HALLWAY",
        "W": "LPNHE_HALLWAY",
        "FEEFIE": "LPNHE_SECRET_ALCOVE",
    },
    "LPNHE_SECRET_ALCOVE": {"OUT": "LPNHE_RC17"},
    "LPNHE_RC19": {
        "OUT": "LPNHE_HALLWAY",
        "COULOIR": "LPNHE_HALLWAY",
        "W": "LPNHE_HALLWAY",
    },
    "SB_23_24": {"S": "SB_24", "N": "SB_23", "E": "SB_33_34"},
    "SB_23_W": {"E": "SB_23", "OUT": "SB_23"},
    "SB_33_43": {
        "W": "SB_33",
        "E": "SB_43",
        "N": "SB_33_43_DEADEND",
        "TIPI": "SB_33_43_DEADEND",
    },
    "SB_43": {
        "E": "SB_43_53",
        "W": "SB_33_43",
        "S": "BACHELOR_LIBRARY_HALL",
        "BIBLIOTHEQUE": "BACHELOR_LIBRARY_HALL",
        "LICENCES": "BACHELOR_LIBRARY_HALL",
        "HALL": "BACHELOR_LIBRARY_HALL",
        "IN": "BACHELOR_LIBRARY_HALL",
    },
    "SB_43_53": {"N": "SB_43_53_DEADEND", "W": "SB_43"},
    "SB_43_53_DEADEND": {"S": "SB_43_53", "OUT": "SB_43_53"},
    "BACHELOR_LIBRARY_HALL": {"OUT": "SB_43", "N": "SB_43"},
    "SB_33_43_DEADEND": {"S": "SB_33_43", "OUT": "SB_33_43"},
    "SB_26_DEADEND": {"N": "SB_26"},
}

NAME_GRAPH = SB_BASE
NAME_GRAPH.update(JU_BASE)
